!!com.github.adminfaces.addon.scaffold.model.GlobalConfig
toOneComponentType: AUTOCOMPLETE
toManyComponentType: CHECKBOXMENU
datatableEditable: false
datatableReflow: true
inputSize: 100
menuIcon: "fa fa-circle-o"